import "./globals.css";
import { Inter, League_Spartan } from "next/font/google";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });
const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  variable: "--font-lSpartan",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//srxRApkQAPZrKGSUCQkK7Qtt

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1"
      ></meta>
      <body className={`${leagueSpartan.variable} font-sans`}>{children}</body>
    </html>
  );
}
